[project]
name = "sfkit"
version = "0.0.111"
authors = [{ name = "Simon Mendelsohn", email = "smendels@broadinstitute.org" }]
description = "Some CLI Tools For The Secure Multi-party Genomic Analysis Website"
readme = "README.md"
requires-python = ">=3.9.2"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'black',
    'checksumdir',
    'google-auth',
    'ipaddr',
    'PyNaCl',
    'requests',
    'toml',
    'tqdm',
]

[project.scripts]
sfkit = "sfkit.cli:main"

[project.urls]
"Website" = "https://sfkit.org/"
"Github" = "https://github.com/simonjmendelsohn/secure-gwas-keys-and-encryption"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["sfkit"]

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]

[tool.pytest.ini_options]
pythonpath = [".", "sfkit", "tests"]
